import { Metadata } from "next";
import { Search } from "lucide-react";
import ToolClient from "./ToolClient";

export const metadata: Metadata = {
  title: "Free YouTube SEO Score (Lite)",
  description:
    "Paste a YouTube video URL and get a fast SEO score plus top fixes. TubeGrow’s lite tool previews our AI YouTube SEO workflows.",
  alternates: { canonical: "/tools/youtube-seo-score" },
};

export default function YouTubeSeoScoreToolPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-zinc-950 via-zinc-900 to-zinc-950">
      <section className="relative pt-24 pb-10 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-purple-500/10 via-transparent to-blue-500/10" />
        <div className="max-w-4xl mx-auto relative text-center">
          <div className="inline-flex items-center gap-2 bg-purple-500/10 border border-purple-500/20 rounded-full px-4 py-2 mb-5">
            <Search className="w-4 h-4 text-purple-400" />
            <span className="text-purple-300 text-sm font-medium">Lite SEO Checker</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Free YouTube SEO Score (Lite)
          </h1>
          <p className="text-zinc-400 mb-6">
            Paste any YouTube video link to get a quick SEO score, a prioritized fix list, and
            better titles/tags generated by TubeGrow AI. This is a preview of our full YouTube SEO tool.
          </p>
        </div>
      </section>

      <ToolClient />
    </div>
  );
}

